### ISSUE TITLE
Wrong Icon-Provider

### ISSUE THREAD

**Issue by Starraider** [wacon-internet-gmbh/wacon_cookie_management#12]
In the ext_localconfig.php in Line 65 and 71 you use the SvgIconProvider for a .png file (Extension.png). As a result, the "new content element" dialog in the backend no longer works!
You should use the BitmapIconProvider instead; or switch back to a .svg icon again.

**Comment by kuschmitt** [comment]
This bug is fixed in Version 1.1.7
