### ISSUE TITLE
Datenschutzlink HTML parsen

### ISSUE THREAD

**Issue by David-Nischk** [wacon-internet-gmbh/wacon_cookie_management#18]
Hallo,

ist es möglich, aus dem Feld für den externen Datenschutz Link einen klickbaren Link generieren zu lassen? Ich habe dazu in der bereitgestellten Dokumentation nichts finden können.

**Comment by lukasdoerr** [comment]
Das musst Du ein bisschen genauer definieren? Es wird doch bereits ein Link generiert? Was meinst du genau?
