### ISSUE TITLE
Cookie Banner wird trotz gesetzten Cookie weiterhin angezeigt

### ISSUE THREAD

**Issue by ews-kupke** [wacon-internet-gmbh/wacon_cookie_management#22]
Hallo,

Wir haben aktuell das Problem mit dem Cookie Manager, dass nachdem eine Auswahl getätigt hat und der waconcookiemanagement gesetzt ist, dass der Banner weiterhin bei jedem reload erscheint.

Wir arbeiten auf einer 9.5er TYPO3 Umgebung.

Ich habe festgestellt, dass wenn man in der waconcookiemanagement.js, innerhalb der document ready Funktion, den Code `$('.waconcookiemanagement').prependTo("body");` nimmt und ihn an den Anfang des else Zweigs verschiebt, dann würde das bei uns das Problem lösen:

`$(document).ready(function () {
 
  var wert = getCookie("waconcookiemanagement");
  if (wert != "") {
    if (wert == "max") { 
      for (i = 0; i < 30; i++) {
        $("cookie-on").show();
        $("cookie-off").hide();
      }
    }
    else {
      res = wert.split("c");
      jQuery.each(res, function (i, val) {
        $(".cookie-on.cookie" + val).show();
        $(".cookie-off.cookie" + val).hide();
      });
    }

  } else {
     $('.waconcookiemanagement').prependTo("body");  
    if (!$(".waconcookiemanagement").hasClass("firsthidden")) {

      $(".waconcookiemanagement").show();

      $("cookieclose").hide();
    }
  }

});`

Könnt Ihr das Problem reproduzieren und würde das unser Problem lösen oder gäbe es da anderweitig Probleme, die wir jetzt nicht überblicken können?

**Comment by wassoli** [comment]
Hallo Herr Kupke,

 

der Fix kann an anderer Stelle zu Problemen führen, das hängt vom Style der Seite ab. 

Normalerweise ist die Box über css auf display: none gesetzt und wird nur sichtbar, wenn kein Cookie gesetzt ist und firsthidden nicht aktiv ist oder  man die Cookieeinstellungen explizit  aktiviert.

 

Vielleicht können Sie das Javascript mal rausnehmen und die Seite aufrufen, dann sollte die Box nicht sichtbar sein. Wenn nicht, müssen Sie die css-Einstellungen prüfen, möglicherweise wird das „display:none“ an anderer Stelle überschrieben. 

 

Kerstin Schmitt

Certified TYPO3 CMS Developer

Certified TYPO3 CMS Integrator

 

WACON Internet GmbH

 

Nollenweg 2

65510 Idstein

Tel.:  0800-9226619

Fax.: 06082-928047

email:  kerstin.schmitt@wacon.de <mailto:kerstin.schmitt@wacon.de> 

web:   www.wacon.de <http://www.wacon.de> 

Handelsregister:

Amtsgericht Wiesbaden, HRB 19439

Geschäftsführer: Oliver Wassenaar

 

 

Kerstin Schmitt

Certified TYPO3 CMS Developer

Certified TYPO3 CMS Integrator

 

WACON Internet GmbH

 

Nollenweg 2

65510 Idstein

Tel.:  0800-9226619

Fax.: 06082-928047

email:  kerstin.schmitt@wacon.de <mailto:kerstin.schmitt@wacon.de> 

web:   www.wacon.de <http://www.wacon.de> 

Handelsregister:

Amtsgericht Wiesbaden, HRB 19439

Geschäftsführer: Oliver Wassenaar

 

Von: ews-kupke <notifications@github.com> 
Gesendet: Freitag, 11. September 2020 12:12
An: wacon-internet-gmbh/wacon_cookie_management <wacon_cookie_management@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [wacon-internet-gmbh/wacon_cookie_management] Cookie Banner wird trotz gesetzten Cookie weiterhin angezeigt (#22)

 

Hallo,

Wir haben aktuell das Problem mit dem Cookie Manager, dass nachdem eine Auswahl getätigt hat und der waconcookiemanagement gesetzt ist, dass der Banner weiterhin bei jedem reload erscheint.

Wir arbeiten auf einer 9.5er TYPO3 Umgebung.

Ich habe festgestellt, dass wenn man in der waconcookiemanagement.js, innerhalb der document ready Funktion, den Code $('.waconcookiemanagement').prependTo("body"); nimmt und ihn an den Anfang des else Zweigs verschiebt, dann würde das bei uns das Problem lösen:

`$(document).ready(function () {

var wert = getCookie("waconcookiemanagement");
if (wert != "") {
if (wert == "max") {
for (i = 0; i < 30; i++) {
$("cookie-on").show();
$("cookie-off").hide();
}
}
else {
res = wert.split("c");
jQuery.each(res, function (i, val) {
$(".cookie-on.cookie" + val).show();
$(".cookie-off.cookie" + val).hide();
});
}

} else {
$('.waconcookiemanagement').prependTo("body");
if (!$(".waconcookiemanagement").hasClass("firsthidden")) {

  $(".waconcookiemanagement").show();
 
 
 
  $("cookieclose").hide();
 
}
 

}

});`

Könnt Ihr das Problem reproduzieren und würde das unser Problem lösen oder gäbe es da anderweitig Probleme, die wir jetzt nicht überblicken können?

**Comment by ews-kupke** [comment]
Vielen Dank für die Rückmeldung,

Ich denke, dass das uns schon etwas weiter hilft. Das Javascript hatten wir probeweise mal heraus genommen und daraufhin wurde der Banner nicht mehr angezeigt. Wie es aussieht, triggert ein JS Code einen show Befehl. Zumindest kommt vom css das display:none, im laufe der Ladezeiten wird aber das style Attribut mit display:block gesetzt. Es sieht auf anhieb nicht aus als ob der Code aus der waconcookiemanagement.js kommt. Die dortigen show Befehle hatte ich mal probeweise auskommentiert.

Komische Sache. 
Für uns Funktioniert der Fix aktuell auf dieser Seite aber dann ist der wohl nicht allgemein gültig.
Es hat uns trotzdem sehr geholfen, ich werde auf unserer Testumgebung noch einmal überprüfen woher das kommen kann aber scheinbar ist es kein Bug an der Extension. Sollte ich das Problem finden, würde ich mich ggf. per E-Mail melden. Ich denke, sollte das Problem in kombination mit anderen (externen) JS Dateien/Funktionen/Bibliotheken liegen, wäre das sicherlich interessant.
 
Ich hatte diese Anfrage noch einmal per E-Mail an die hier angegebene Adresse gesendet. Die kann somit gerne ignoriert werden.

Vielen Dank noch einmal.
