### ISSUE TITLE
Conflict with pagelist and personnel Extensions

### ISSUE THREAD

**Issue by mikeemike7** [wacon-internet-gmbh/wacon_cookie_management#36]
Finally a Consent Manager that is clear and works fine! :-)
However, there is a conflict with the extensions Pagelist and Personnel for microtemplate extension: the constants for the breakpoints no longer work when wacon_cookie_management is added. Any idea where to start?

...So, the "error" is in the setup.typoscript: if the lines for loading the jquery.min.js are commented out there, everything seems to work fine (jquery.min.js already exists in v3.6.0 an WCM tries to load v3.2.1.). Can this (loading jquery) be solved in upcomming versions more elegantly, e.g. via constants in the BE?

**Comment by PKuhlmay** [comment]
Hi @mikeemike7 

Can you please check if the error disappears with the branch `add-possibility-to-disable-jquery` ? 
I added a switch with which you can disable the loading of jQuery inside the extension. If you disable it, jQuery will not be loaded. 
Inside the template module, go to constant editor and edit the constant for `tx_waconcookiemanagement_cookiefreigabe.settings.includeJQuery`

**Comment by mikeemike7** [comment]
It was due to the outdated jquery version. Thanks for the work!
