### ISSUE TITLE
PHP-Warnings unter Configuration Preset "Debug"

### ISSUE THREAD

**Issue by amDevDept** [wacon-internet-gmbh/wacon_cookie_management#54]
Hallo,
in Typo3 11 wird beim Versuch, das WCM-Plugin zu rendern. eine php-Warnung ausgegeben. Diese verhindert, dass unter den Configuration-Preset-Bedingungen "Debug" (Debug settings) am System gearbeitet werden kann, da das Frontend immer diese Warnung bringt. Gleich vorab: Ja, wenn man an allen Stellen die php-Warnungen unterdrückt, dann funktioniert es. Ändert man in den Configuration Presets die Debug settings auf "Live" funktioniert ebenfalls alles.
In CookieController.php wird in Zeile 70 versucht, den WCM-Cookie auszulesen, der nach Erstinstallation und -konfiguration der Extension noch nicht da ist. Ca. Zeile 92 dann nochmals.
Das WCM-Backend-Modul bringt ebenfalls eine php-Fehlermeldung unter den Bedingungen Configuration Presets --> Debug Settings --> "Debug". Auch hier: im "Live"-Modus oder mit Unterdrückung der php-Fehlermeldungen funktioniert alles.

**Comment by PKuhlmay** [comment]
Hallo @amDevDept 
Könnten Sie die exakte PHP Warnung, bzw. die Fehlermeldungen hier mit in das Issue rein schreiben? Ich schau mir das dann mal an.
Danke.

**Comment by amDevDept** [comment]
Ja gern: 
`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "waconcookiemanagement" in /var/www/vhosts/ibes-ag.de/httpdocs/public/typo3conf/ext/wacon_cookie_management/Classes/Controller/CookieController.php line 71`

**Um das nachzuvollziehen, muss vorher der evtl. schon vorhandene Cookie "waconcookiemanagement" gelöscht werden.** 
Und: 

- ich arbeite mit der Einstellung "BE --> Einstellungen --> Configuration Presets --> Debug settings --> Debug"
- Mit "BE --> Einstellungen --> Configuration Presets --> Debug settings --> Live" funktioniert alles
![screenshot_Backend-Modul](https://user-images.githubusercontent.com/16936207/187690473-acb63794-af76-4c63-96b0-13a2ff7f68f9.png)
![screenshot_Debug_Settings](https://user-images.githubusercontent.com/16936207/187690476-40fbeb39-691c-4308-95b1-3a1b2854eb00.png)
![screenshot_WCM-Plugin_Frontend](https://user-images.githubusercontent.com/16936207/187690480-6ac83761-fa96-4db2-881b-3a3d79a28af9.png)

**Comment by amDevDept** [comment]
Und nochmal als Screenshot (FE, BE, Debug Settings):
![screenshot_Backend-Modul](https://user-images.githubusercontent.com/16936207/187691806-30cf2e50-ea32-4f43-aa3f-e1b74d68916d.png)
![screenshot_Debug_Settings](https://user-images.githubusercontent.com/16936207/187691808-aee4dddf-82c4-4e88-b5a8-65530ad6a517.png)
![screenshot_WCM-Plugin_Frontend](https://user-images.githubusercontent.com/16936207/187691810-031d4047-8d60-42b8-bf8b-6272849bf3eb.png)

**Comment by PKuhlmay** [comment]
Nur ab PHP 8.0.
Bei PHP 7.4 kommt der Fehler nicht.
