### ISSUE TITLE
WCM Report Crash - zu viele Einträge in DB!

### ISSUE THREAD

**Issue by uv21** [wacon-internet-gmbh/wacon_cookie_management#58]
Hallo,
bei uns im BE kann der WCM Report nicht mehr angezeigt werden (Fatal error: Allowed memory size...), da wir offensichtlich mittlerweile zu viele Einträge in der Datenbanktabelle haben.
Die Tabelle **tx_waconcookiemanagement_domain_model_stat** ist über 140MB groß und hat knapp 1,6 Millionen Einträge..
Kann der Report irgendwie (zb. per Typoscript) deaktiviert werden?
Kann die Tabelle **tx_waconcookiemanagement_domain_model_stat**  geleert werden, ohne das irgendwo Probleme auftauchen könnten?

**Comment by kuschmitt** [comment]
in der Version 3.4.0 ist eine zeitliche Begrenzung eingebaut. Über TypoScript kann der Zeitraum auch auf 0 gesetzt werden, dann wird keine mehr Statistik angelegt
