### ISSUE TITLE
Undefined Variable $years (PHP8)

### ISSUE THREAD

**Issue by PKuhlmay** [wacon-internet-gmbh/wacon_cookie_management#61]
## Bug Report
`PHP Warning: Undefined variable $years in /ext/wacon_cookie_management/Classes/Controller/StatController.php line 73
`

**Environment**
- wacon_cookie_management version(s): 3.3.0
- TYPO3 version(s): 11.5.14
- PHP version(s): 8.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by kuschmitt** [comment]
bugfix in version 3.4.0
