### ISSUE TITLE
Classes for "I accept" button are wrong. Button is clickable for the whole content width.

### ISSUE THREAD

**Issue by PKuhlmay** [wacon-internet-gmbh/wacon_cookie_management#66]
## Bug Report

At the moment the link for the button "I accept" is clickable for the whole content width, instead of the button itself.
The p-tag has the class `cookie-accept`. Instead, the p-tag should have `display: flex` and the a-tag inside should have `cookie-accept`.

**Comment by kuschmitt** [comment]
Version 3.5.0
