### ISSUE TITLE
Cache of top level page gets deleted on every view

### ISSUE THREAD

**Issue by annda** [wacon-internet-gmbh/wacon_cookie_management#69]
This extension prevents TYPO3 caching from working properly, in my case for the main page of the site.

This is because when a new stat record is created, which is on every view, the cache of its parent gets deleted. Unfortunately, here the `pid` is hardcoded to be the uid of the topmost page. The result is that the entry page of my site is never cached.

I will submit a PR with a minimal fix.

**Comment by kuschmitt** [comment]
solution  in version 3.5.0
