### ISSUE TITLE
[BUG] Undefined array key "change"

### ISSUE THREAD

**Issue by PKuhlmay** [wacon-internet-gmbh/wacon_cookie_management#76]
## Bug Report

**Expected behavior**
With PHP 8.2 and WCM 3.4.0 I get the following error:
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "change" in /html/typo3/typo3conf/ext/wacon_cookie_management/Classes/Controller/CookieController.php line 75
```

With PHP 8.1 it worked.

**Environment**
- wacon_cookie_management version(s): 3.4.0
- TYPO3 version(s): 11.5.21
- PHP version(s): 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by kuschmitt** [comment]
Solved in 3.5.0
