### ISSUE TITLE
Avoid php Warnings Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "header" in /html/typo3/typo3conf/ext/wacon_cookie_management/Classes/Controller/CookieController.php line 66 

### ISSUE THREAD

**Issue by christophrunkel** [wacon-internet-gmbh/wacon_cookie_management#80]
## Bug Report

Controller causes php warnings in PHP 8.2

**Current Behavior**
Undefined array key "header" in /html/typo3/typo3conf/ext/wacon_cookie_management/Classes/Controller/CookieController.php line 66 

**Environment**
- wacon_cookie_management version(s): [e.g. 4.0.1]
- TYPO3 version(s): [e.g. 12.4.8]
- PHP version(s): [8.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Possible Solution**

Adding ?? null in line 66 ff fixes the problem.

 $header = $this->settings['header'] ?? null;
      $this->view->assign('header', $header);
      $teaser = $this->settings['teaser'] ?? null;
      $this->view->assign('teaser', $teaser);
      $linktext = $this->settings['linktext'] ?? null;
      $this->view->assign('linktext', $linktext);
      $imprint = $this->settings['imprint'] ?? null;
        $this->view->assign('imprint', $imprint);
        $dataprotection = $this->settings['dataProtection'] ?? null;
        $this->view->assign('dataprotection', $dataprotection );
        $nurlink = $this->settings['nurLink'] ?? null;

**Comment by PKuhlmay** [comment]
Solved in https://github.com/wacon-internet-gmbh/wacon_cookie_management/commit/22a720f37a0dfcba961a384f51325302211c446e
