### ISSUE TITLE
Placeholder images in the script plugin are not assigned correctly

### ISSUE THREAD

**Issue by m10a** [wacon-internet-gmbh/wacon_cookie_management#84]
## Bug Report
Placeholder images from settings.bild in the script plugin (waconcookiemanagement_script) are no longer displayed in TYPO3 12

**Expected behavior**
Until TYPO3 11, images uploaded to the mentioned field in the Flexform plugin were assigned to the tt_content images field.

**Current Behavior**
In TYPO3 12 the images are not mapped and so they are not available in the fluid template.

**Steps to reproduce**
In the screenshot below the first line shows the old correct behaviour. The image was assigned before upgrading to Version 12. The second line shows the current behaviour.
![filelist-view](https://github.com/user-attachments/assets/0d997ec0-0e82-4d12-894f-4aab3bfa4f52)

**Environment**
- wacon_cookie_management version(s): 4.1.1
- TYPO3 version(s): 12
- PHP version(s): 8.3
- Is your TYPO3 installation set up with Composer (Composer Mode): both

**Comment by kuschmitt** [comment]
Solved in Version 6
